<a href="https://colab.research.google.com/github/Chaitanya-Shikhare/Football-Penalty-Prediction/blob/main/Football_Penalty_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [35]:
df = pd.read_csv("penalty.csv")
df.head()

index  period  minute  ...  stadium  direction  outcome
0      0       2      92  ...        5          8        1
1      1       2      62  ...        5          5        1
2      2       2      67  ...        5          9        1
3      3       1      31  ...        5          4        1
4      4       1      38  ...        5          2        1

[5 rows x 23 columns]

In [36]:
df.describe()

index      period      minute  ...     stadium   direction     outcome
count  352.000000  352.000000  352.000000  ...  352.000000  352.000000  352.000000
mean   175.500000    2.343750   69.321023  ...   35.142045    5.781250    0.750000
std    101.757883    1.439577   35.823273  ...   27.642142    2.563249    0.433629
min      0.000000    1.000000    1.000000  ...    0.000000    0.000000    0.000000
25%     87.750000    1.000000   40.750000  ...    5.000000    4.000000    0.750000
50%    175.500000    2.000000   68.500000  ...   34.500000    5.000000    1.000000
75%    263.250000    2.000000   92.000000  ...   64.000000    8.000000    1.000000
max    351.000000    5.000000  128.000000  ...   75.000000    9.000000    1.000000

[8 rows x 23 columns]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 352 entries, 0 to 351
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   index                  352 non-null    int64  
 1   period                 352 non-null    int64  
 2   minute                 352 non-null    int64  
 3   second                 352 non-null    int64  
 4   possession             352 non-null    int64  
 5   duration               352 non-null    float64
 6   statsbomb_xg           352 non-null    float64
 7   penalty_taken_at_home  350 non-null    float64
 8   home_score             350 non-null    float64
 9   away_score             350 non-null    float64
 10  match_week             350 non-null    float64
 11  player_team_name       352 non-null    int64  
 12  player_name            352 non-null    int64  
 13  player_position        352 non-null    int64  
 14  foot                   352 non-null    int64  
 15  techni

In [38]:
df.isnull().sum()

index                    0
period                   0
minute                   0
second                   0
possession               0
duration                 0
statsbomb_xg             0
penalty_taken_at_home    2
home_score               2
away_score               2
match_week               2
player_team_name         0
player_name              0
player_position          0
foot                     0
technique                0
keeper_name              0
keeper_team_name         0
competition_name         0
competition_stage        0
stadium                  0
direction                0
outcome                  0
dtype: int64

In [39]:
df["penalty_taken_at_home"].fillna(df["penalty_taken_at_home"].mean(),inplace=True)
df["home_score"].fillna(df["home_score"].mean(),inplace=True)
df["away_score"].fillna(df["away_score"].mean(),inplace=True)
df["match_week"].fillna(df["match_week"].mean(),inplace=True)
df.isnull().sum()

index                    0
period                   0
minute                   0
second                   0
possession               0
duration                 0
statsbomb_xg             0
penalty_taken_at_home    0
home_score               0
away_score               0
match_week               0
player_team_name         0
player_name              0
player_position          0
foot                     0
technique                0
keeper_name              0
keeper_team_name         0
competition_name         0
competition_stage        0
stadium                  0
direction                0
outcome                  0
dtype: int64

In [40]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values
X, y

(array([[  0.,   2.,  92., ...,   3.,   5.,   8.],
        [  1.,   2.,  62., ...,   3.,   5.,   5.],
        [  2.,   2.,  67., ...,   3.,   5.,   9.],
        ...,
        [349.,   2.,  63., ...,   3.,  24.,   1.],
        [350.,   2.,  47., ...,   3.,  26.,   9.],
        [351.,   2.,  86., ...,   3.,   5.,   8.]]),
 array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
        1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1,

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [42]:
X_test

array([[  6.,   2.,  84., ...,   3.,   5.,   8.],
       [ 52.,   2.,  61., ...,   3.,   1.,   6.],
       [259.,   2.,  71., ...,   3.,  13.,   9.],
       ...,
       [ 22.,   2.,  47., ...,   0.,  62.,   9.],
       [340.,   5., 125., ...,   2.,  43.,   5.],
       [309.,   5., 124., ...,   4.,  65.,   2.]])

In [43]:
X_train

array([[142.,   2.,  52., ...,   3.,  21.,   7.],
       [258.,   1.,  22., ...,   3.,  13.,   5.],
       [ 66.,   2.,  65., ...,   3.,  46.,   9.],
       ...,
       [117.,   1.,  38., ...,   3.,   5.,   4.],
       [ 47.,   2.,  55., ...,   3.,  66.,   6.],
       [172.,   2.,  73., ...,   3.,  75.,   8.]])

In [44]:
y_train

array([1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1])

In [45]:
y_test

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1])

In [46]:
#sns.pairplot(df, hue='outcome', size=5)

In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [48]:
X_train

array([[-0.36036894, -0.27400341, -0.49937907, ...,  0.29662877,
        -0.54793988,  0.49852074],
       [ 0.76724304, -0.95004922, -1.32164148, ...,  0.29662877,
        -0.83826828, -0.28023355],
       [-1.09914921, -0.27400341, -0.14306535, ...,  0.29662877,
         0.35933639,  1.27727502],
       ...,
       [-0.60338877, -0.95004922, -0.88310153, ...,  0.29662877,
        -1.12859669, -0.66961069],
       [-1.28384427, -0.27400341, -0.41715283, ...,  0.29662877,
         1.0851574 ,  0.10914359],
       [-0.06874515, -0.27400341,  0.07620462, ...,  0.29662877,
         1.41177685,  0.88789788]])

In [49]:
X_test

array([[-1.68239678, -0.27400341,  0.37770084, ...,  0.29662877,
        -1.12859669,  0.88789788],
       [-1.23524031, -0.27400341, -0.25270034, ...,  0.29662877,
        -1.27376089,  0.10914359],
       [ 0.77696383, -0.27400341,  0.02138713, ...,  0.29662877,
        -0.83826828,  1.27727502],
       ...,
       [-1.5268641 , -0.27400341, -0.6364228 , ..., -2.34303396,
         0.9399932 ,  1.27727502],
       [ 1.56434806,  1.75413401,  1.50145948, ..., -0.58325881,
         0.25046324, -0.28023355],
       [ 1.26300348,  1.75413401,  1.47405073, ...,  1.17651634,
         1.04886635, -1.44836498]])

In [50]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [51]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]]


In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 2 17]
 [ 1 68]]


0.7954545454545454